-- SCRIPT SIMPLE PARA MIGRAR FK DE ASISTENCIA
-- Ejecutar comandos uno por uno para mayor control

-- 1. VERIFICAR ESTADO ACTUAL
SELECT 'Verificando FK constraints actuales...' as status;

SELECT 
    CONSTRAINT_NAME,
    COLUMN_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA = DATABASE()
AND TABLE_NAME = 'asistencia'
AND REFERENCED_TABLE_NAME IS NOT NULL;

-- 2. CREAR TABLA EMPLEADO_HORARIO_PERSONALIZADO
CREATE TABLE IF NOT EXISTS empleado_horario_personalizado (
    ID_EMPLEADO_HORARIO INT AUTO_INCREMENT PRIMARY KEY,
    ID_EMPLEADO INT NOT NULL,
    ID_DIA INT NOT NULL,
    HORA_ENTRADA TIME NOT NULL,
    HORA_SALIDA TIME NOT NULL,
    TOLERANCIA INT DEFAULT 15,
    NOMBRE_TURNO VARCHAR(50) DEFAULT 'Turno Principal',
    FECHA_DESDE DATE NOT NULL,
    FECHA_HASTA DATE NULL,
    ACTIVO CHAR(1) DEFAULT 'S',
    ORDEN_TURNO INT DEFAULT 1,
    OBSERVACIONES TEXT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (ID_EMPLEADO) REFERENCES empleado(ID_EMPLEADO) ON DELETE CASCADE,
    FOREIGN KEY (ID_DIA) REFERENCES dia_semana(ID_DIA),
    INDEX idx_empleado_dia_activo (ID_EMPLEADO, ID_DIA, ACTIVO)
);

-- 3. AGREGAR COLUMNA ID_EMPLEADO_HORARIO A ASISTENCIA
-- EJECUTAR SOLO SI LA COLUMNA NO EXISTE
-- ALTER TABLE asistencia ADD COLUMN ID_EMPLEADO_HORARIO INT NULL;

-- 4. ELIMINAR FK DE ID_HORARIO
-- Primero encontrar el nombre del constraint (ejecutar esta query)
SELECT 
    CONSTRAINT_NAME,
    'Ejecutar: ALTER TABLE asistencia DROP FOREIGN KEY ' + CONSTRAINT_NAME + ';' as comando_a_ejecutar
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA = DATABASE()
AND TABLE_NAME = 'asistencia'
AND COLUMN_NAME = 'ID_HORARIO'
AND REFERENCED_TABLE_NAME = 'horario';

-- 5. DESPUÉS DE OBTENER EL NOMBRE DEL CONSTRAINT, EJECUTAR:
-- ALTER TABLE asistencia DROP FOREIGN KEY nombre_del_constraint;

-- 6. CREAR NUEVO FK HACIA EMPLEADO_HORARIO_PERSONALIZADO
-- ALTER TABLE asistencia 
-- ADD CONSTRAINT fk_asistencia_empleado_horario 
-- FOREIGN KEY (ID_EMPLEADO_HORARIO) 
-- REFERENCES empleado_horario_personalizado(ID_EMPLEADO_HORARIO) 
-- ON DELETE SET NULL ON UPDATE CASCADE;

-- 7. CREAR ÍNDICES
-- CREATE INDEX idx_asistencia_empleado_horario ON asistencia(ID_EMPLEADO_HORARIO);
-- CREATE INDEX idx_asistencia_empleado_fecha ON asistencia(ID_EMPLEADO, FECHA, TIPO);

-- 8. VERIFICAR RESULTADO
-- DESCRIBE asistencia;